window.ASMR_VIDEOS = [
  {
    id: "sample-miko-001",
    youtubeId: "",
    title: "睡眠導入ASMR サンプル",
    member: "さくらみこ",
    status: "active",
    branch: "JP",
    generation: "0期生",
    date: "2026-01-12",
    duration: "1:42:00",
    language: ["ja"],
    tags: ["睡眠導入", "囁き", "耳かき", "日本語"],
    equipment: ["KU100"],
    note: "実データ追加時に公式配信URLへ差し替えてください。",
    sample: true
  },
  {
    id: "sample-okayu-001",
    youtubeId: "",
    title: "まったり囁きASMR サンプル",
    member: "猫又おかゆ",
    status: "active",
    branch: "JP",
    generation: "ゲーマーズ",
    date: "2025-11-03",
    duration: "2:08:30",
    language: ["ja"],
    tags: ["囁き", "雑談少なめ", "睡眠導入", "日本語"],
    equipment: ["バイノーラル"],
    note: "MVP確認用のサンプルです。",
    sample: true
  },
  {
    id: "sample-choco-001",
    youtubeId: "",
    title: "耳かきロールプレイASMR サンプル",
    member: "癒月ちょこ",
    status: "active",
    branch: "JP",
    generation: "2期生",
    date: "2025-09-22",
    duration: "1:26:44",
    language: ["ja"],
    tags: ["耳かき", "ロールプレイ", "近距離", "日本語"],
    equipment: ["KU100"],
    note: "MVP確認用のサンプルです。",
    sample: true
  },
  {
    id: "sample-fauna-001",
    youtubeId: "",
    title: "Soft Whisper ASMR Sample",
    member: "Ceres Fauna",
    status: "graduated",
    branch: "EN",
    generation: "Council",
    date: "2024-08-10",
    duration: "1:58:11",
    language: ["en"],
    tags: ["Whisper", "Sleep", "No BGM", "English"],
    equipment: ["Binaural"],
    note: "卒業生表示の動作確認用サンプルです。",
    sample: true
  },
  {
    id: "sample-aqua-001",
    youtubeId: "",
    title: "深夜の睡眠導入ASMR サンプル",
    member: "湊あくあ",
    status: "graduated",
    branch: "JP",
    generation: "2期生",
    date: "2024-06-30",
    duration: "1:12:09",
    language: ["ja"],
    tags: ["睡眠導入", "囁き", "BGMなし", "日本語"],
    equipment: ["バイノーラル"],
    note: "卒業生表示の動作確認用サンプルです。",
    sample: true
  },
  {
    id: "sample-zeta-001",
    youtubeId: "",
    title: "Cozy Night ASMR Sample",
    member: "Vestia Zeta",
    status: "active",
    branch: "ID",
    generation: "ID 3期生",
    date: "2025-10-04",
    duration: "1:36:20",
    language: ["id", "en"],
    tags: ["Whisper", "Sleep", "Close-up", "English"],
    equipment: ["Binaural"],
    note: "多言語フィルター確認用サンプルです。",
    sample: true
  }
];
